#ifndef _TABLE_H_
#define _TABLE_H_

#include "tokens.h"
#include <map>
#include <vector>
#include <utility>
#include <iostream>

enum NonTerminals {
    PROGRAM = 500,
    DECL,
    CONSTS,
    LISTCONST,
    LISTCONSTPRIME,
    CONSTDECL,
    TYPES,
    TYPESPRIME,
    PRIMTYPES,
    ARRAYTYPE,
    SUBRANGELIST,
    SUBRANGEPRIME,
    SUBRANGELISTPRIME,
    SUBRANGETYPE,
    SETTYPE,
    ENUMTYPE,
    RECORDTYPE,
    USERTYPES,
    LISTUSERTYPES,
    LISTUSERTYPESPRIME,
    USERTYPE,
    VARS,
    VARLISTLIST,
    VARLISTLISTPRIME,
    VARLIST,
    IDLIST,
    IDLISTPRIME,
    IDATTR,
    VARIABLE,
    VARIABLEPRIME,
    BLOCK,
    STMTS,
    STMTLISTPRIME,
    STMT,
    STMTPRIME,
    SUBPROGCALL,
    EXITSTMT,
    RETURNSTMT,
    ATTRSTMT,
    ATTRSTMTPRIME,
    IFBLOCK,
    ELSEBLOCK,
    LOOPBLOCK,
    CASEBLOCK,
    CASEBLOCKPRIME,
    CASELIST,
    LITERALLIST,
    LITERALLISTPRIME,
    GOTOSTMT,
    FORBLOCK,
    FORBLOCKPRIME,
    EXPR,
    DISJ,
    FINAL_TERM,
    FINAL_TERMPRIME,
    ADD_OP,
    MUL_OP,
    EQUALITY_OP,
    RELATIONAL_OP,
    CONJ,
    CONJPRIME,
    COMP,
    COMPPRIME,
    RELATIONAL,
    RELATIONALPRIME,
    SUM,
    SUMPRIME,
    NEG,
    MUL,
    MULPRIME,
    LITERAL,
    EXPRLIST,
    EXPRLISTPLUS,
    EXPRLISTPLUSPRIME,
    SUBPROGRAMS,
    SUBPROGRAMSPRIME,
    PROCEDURE,
    FUNCTION,
    PARAM,
    PARAMLISTLIST,
    PARAMLISTLISTPRIME,
    PARAMLIST,
    WRITESTMT,
    WRITELNSTMT,
    READSTMT,
    READLNSTMT
};

std::map<std::pair<int, int>, std::vector<int>> table;


void init_table() {
    //PROGRAM
    table[{PROGRAM, PROGRAM_TOKEN}] = {PROGRAM_TOKEN, ID_TOKEN, ';', DECL, BLOCK, '.'};
    // DECL
    table[{DECL, CONST_TOKEN}] = {CONSTS, USERTYPES, VARS, SUBPROGRAMS};
    table[{DECL, TYPE_TOKEN}] = {CONSTS, USERTYPES, VARS, SUBPROGRAMS};
    table[{DECL, VAR_TOKEN}] = {CONSTS, USERTYPES, VARS, SUBPROGRAMS};
    table[{DECL, BEGIN_TOKEN}] = {CONSTS, USERTYPES, VARS, SUBPROGRAMS};
    table[{DECL, FUNC_TOKEN}] = {CONSTS, USERTYPES, VARS, SUBPROGRAMS};
    table[{DECL, PROC_TOKEN}] = {CONSTS, USERTYPES, VARS, SUBPROGRAMS};
    // CONSTS
    table[{CONSTS, CONST_TOKEN}] = {CONST_TOKEN, LISTCONST};
    table[{CONSTS, VAR_TOKEN}] = {};
    table[{CONSTS, PROC_TOKEN}] = {};
    table[{CONSTS, FUNC_TOKEN}] = {};
    table[{CONSTS, TYPE_TOKEN}] = {};
    table[{CONSTS, BEGIN_TOKEN}] = {};
    // LISTCONST
    table[{LISTCONST, ID_TOKEN}] = {CONSTDECL, LISTCONSTPRIME};
    // LISTCONSTPRIME
    table[{LISTCONSTPRIME, ID_TOKEN}] = {LISTCONST};
    table[{LISTCONSTPRIME, VAR_TOKEN}] = {};
    table[{LISTCONSTPRIME, PROC_TOKEN}] = {};
    table[{LISTCONSTPRIME, FUNC_TOKEN}] = {};
    table[{LISTCONSTPRIME, TYPE_TOKEN}] = {};
    table[{LISTCONSTPRIME, BEGIN_TOKEN}] = {};
    // CONSTDECL
    table[{CONSTDECL, ID_TOKEN}] = {ID_TOKEN, '=', EXPR, ';'};
    // TYPES
    table[{TYPES, ID_TOKEN}] = {ID_TOKEN, TYPESPRIME};
    table[{TYPES, INT_TOKEN}] = {PRIMTYPES};
    table[{TYPES, REAL_TOKEN}] = {PRIMTYPES};
    table[{TYPES, BOOL_TOKEN}] = {PRIMTYPES};
    table[{TYPES, CHAR_TOKEN}] = {PRIMTYPES};
    table[{TYPES, STRING_TOKEN}] = {PRIMTYPES};
    table[{TYPES, ARRAY_TOKEN}] = {PRIMTYPES};
    table[{TYPES, RECORD_TOKEN}] = {PRIMTYPES};
    table[{TYPES, '('}] = {PRIMTYPES};
    table[{TYPES, SET_TOKEN}] = {PRIMTYPES};
    // TYPESPRIME
    table[{TYPESPRIME, RANGE_TOKEN}] = {RANGE_TOKEN, SUBRANGETYPE};
    table[{TYPESPRIME, ID_TOKEN}] = {};
    table[{TYPESPRIME, ';'}] = {};
    // PRIMTYPES
    table[{PRIMTYPES, INT_TOKEN}] = {INT_TOKEN, TYPESPRIME};
    table[{PRIMTYPES, REAL_TOKEN}] = {REAL_TOKEN};
    table[{PRIMTYPES, BOOL_TOKEN}] = {BOOL_TOKEN};
    table[{PRIMTYPES, CHAR_TOKEN}] = {CHAR_TOKEN, TYPESPRIME};
    table[{PRIMTYPES, STRING_TOKEN}] = {STRING_TOKEN};
    table[{PRIMTYPES, ARRAY_TOKEN}] = {ARRAYTYPE};
    table[{PRIMTYPES, RECORD_TOKEN}] = {RECORDTYPE};
    table[{PRIMTYPES, SET_TOKEN}] = {SETTYPE};
    table[{PRIMTYPES, '('}] = {ENUMTYPE};
    // ARRAYTYPE
    table[{ARRAYTYPE, ARRAY_TOKEN}] = {ARRAY_TOKEN, '[', SUBRANGELIST, ']', OF_TOKEN, TYPES};
    // SUBRANGELIST
    table[{SUBRANGELIST, ID_TOKEN}] = {ID_TOKEN, SUBRANGEPRIME};
    table[{SUBRANGELIST, INT_TOKEN}] = {INT_TOKEN, RANGE_TOKEN, SUBRANGETYPE, SUBRANGELISTPRIME};
    table[{SUBRANGELIST, CHAR_TOKEN}] = {CHAR_TOKEN, RANGE_TOKEN, SUBRANGETYPE, SUBRANGELISTPRIME};
    // SUBRANGEPRIME
    table[{SUBRANGEPRIME, RANGE_TOKEN}] = {RANGE_TOKEN, SUBRANGETYPE, SUBRANGELISTPRIME};
    table[{SUBRANGEPRIME, ']'}] = {SUBRANGELISTPRIME};
    table[{SUBRANGEPRIME, ','}] = {SUBRANGELISTPRIME};
    // SUBRANGELISTPRIME
    table[{SUBRANGELISTPRIME, ','}] = {',', SUBRANGELIST};
    table[{SUBRANGELISTPRIME, ']'}] = {};
    // SUBRANGETYPE
    table[{SUBRANGETYPE, ID_TOKEN}] = {ID_TOKEN};
    table[{SUBRANGETYPE, INT_TOKEN}] = {INT_TOKEN};
    table[{SUBRANGETYPE, CHAR_TOKEN}] = {CHAR_TOKEN};
    // SETTYPE
    table[{SETTYPE, SET_TOKEN}] = {SET_TOKEN, OF_TOKEN, TYPES};
    // ENUMTYPE
    table[{ENUMTYPE, '('}] = {'(', IDLIST, ')'};
    // RECORDTYPE
    table[{RECORDTYPE, RECORD_TOKEN}] = {RECORD_TOKEN, VARLISTLIST, END_TOKEN};
    // USERTYPES
    table[{USERTYPES, TYPE_TOKEN}] = {TYPE_TOKEN, LISTUSERTYPES};
    table[{USERTYPES, VAR_TOKEN}] = {};
    table[{USERTYPES, PROC_TOKEN}] = {};
    table[{USERTYPES, FUNC_TOKEN}] = {};
    table[{USERTYPES, BEGIN_TOKEN}] = {};
    // LISTUSERTYPES
    table[{LISTUSERTYPES, ID_TOKEN}] = {USERTYPE, LISTUSERTYPESPRIME};
    // LISTUSERTYPESPRIME
    table[{LISTUSERTYPESPRIME, ID_TOKEN}] = {LISTUSERTYPES};
    table[{LISTUSERTYPESPRIME, VAR_TOKEN}] = {};
    table[{LISTUSERTYPESPRIME, BEGIN_TOKEN}] = {};
    table[{LISTUSERTYPESPRIME, PROC_TOKEN}] = {};
    table[{LISTUSERTYPESPRIME, FUNC_TOKEN}] = {};
    // USERTYPE
    table[{USERTYPE, ID_TOKEN}] = {ID_TOKEN, '=', TYPES, ';'};
    // VARS
    table[{VARS, VAR_TOKEN}] = {VAR_TOKEN, VARLISTLIST};
    table[{VARS, PROC_TOKEN}] = {};
    table[{VARS, FUNC_TOKEN}] = {};
    table[{VARS, BEGIN_TOKEN}] = {};
    // VARLISTLIST
    table[{VARLISTLIST, ID_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, INT_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, REAL_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, BOOL_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, CHAR_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, STRING_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, ARRAY_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, SET_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, '('}] = {VARLIST, VARLISTLISTPRIME};
    table[{VARLISTLIST, RECORD_TOKEN}] = {VARLIST, VARLISTLISTPRIME};
    // VARLISTLISTPRIME
    table[{VARLISTLISTPRIME, '('}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, ID_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, INT_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, REAL_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, BOOL_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, CHAR_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, STRING_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, ARRAY_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, SET_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, RECORD_TOKEN}] = {VARLISTLIST};
    table[{VARLISTLISTPRIME, END_TOKEN}] = {};
    table[{VARLISTLISTPRIME, BEGIN_TOKEN}] = {};
    table[{VARLISTLISTPRIME, PROC_TOKEN}] = {};
    table[{VARLISTLISTPRIME, FUNC_TOKEN}] = {};
    // VARLIST
    table[{VARLIST, '('}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, ID_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, INT_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, REAL_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, BOOL_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, CHAR_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, STRING_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, ARRAY_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, SET_TOKEN}] = {TYPES, IDLIST, ';'};
    table[{VARLIST, RECORD_TOKEN}] = {TYPES, IDLIST, ';'};
    // IDLIST
    table[{IDLIST, ID_TOKEN}] = {ID_TOKEN, IDATTR, IDLISTPRIME};
    // IDLISTPRIME
    table[{IDLISTPRIME, ','}] = {',', IDLIST};
    table[{IDLISTPRIME, ';'}] = {};
    table[{IDLISTPRIME, ')'}] = {};
    // IDATTR
    table[{IDATTR, '='}] = {'=', EXPR};
    table[{IDATTR, ';'}] = {};
    table[{IDATTR, ','}] = {};
    table[{IDATTR, ')'}] = {};
    // VARIABLE
    table[{VARIABLE, '['}] = {'[', EXPRLISTPLUS, ']', VARIABLEPRIME};
    table[{VARIABLE, ACCESS_TOKEN}] = {ACCESS_TOKEN, ID_TOKEN, VARIABLEPRIME};
    // VARIABLEPRIME
    table[{VARIABLEPRIME, ACCESS_TOKEN}] = {VARIABLE};
    table[{VARIABLEPRIME, '['}] = {VARIABLE};
    table[{VARIABLEPRIME, ';'}] = {};
    table[{VARIABLEPRIME, ']'}] = {};
    table[{VARIABLEPRIME, ','}] = {};
    table[{VARIABLEPRIME, ')'}] = {};
    table[{VARIABLEPRIME, '+'}] = {};
    table[{VARIABLEPRIME, '-'}] = {};
    table[{VARIABLEPRIME, '*'}] = {};
    table[{VARIABLEPRIME, '/'}] = {};
    table[{VARIABLEPRIME, '%'}] = {};
    table[{VARIABLEPRIME, '<'}] = {};
    table[{VARIABLEPRIME, '>'}] = {};
    table[{VARIABLEPRIME, ID_TOKEN}] = {};
    table[{VARIABLEPRIME, OF_TOKEN}] = {};
    table[{VARIABLEPRIME, END_TOKEN}] = {};
    table[{VARIABLEPRIME, BEGIN_TOKEN}] = {};
    table[{VARIABLEPRIME, LABEL_TOKEN}] = {};
    table[{VARIABLEPRIME, EXITWHEN_TOKEN}] = {};
    table[{VARIABLEPRIME, RETURN_TOKEN}] = {};
    table[{VARIABLEPRIME, ATTR_TOKEN}] = {};
    table[{VARIABLEPRIME, IF_TOKEN}] = {};
    table[{VARIABLEPRIME, ELSE_TOKEN}] = {};
    table[{VARIABLEPRIME, LOOP_TOKEN}] = {};
    table[{VARIABLEPRIME, CASE_TOKEN}] = {};
    table[{VARIABLEPRIME, GOTO_TOKEN}] = {};
    table[{VARIABLEPRIME, FOR_TOKEN}] = {};
    table[{VARIABLEPRIME, TO_TOKEN}] = {};
    table[{VARIABLEPRIME, STEP_TOKEN}] = {};
    table[{VARIABLEPRIME, DO_TOKEN}] = {};
    table[{VARIABLEPRIME, OR_TOKEN}] = {};
    table[{VARIABLEPRIME, EQUAL_TOKEN}] = {};
    table[{VARIABLEPRIME, DIFF_TOKEN}] = {};
    table[{VARIABLEPRIME, LE_TOKEN}] = {};
    table[{VARIABLEPRIME, GE_TOKEN}] = {};
    table[{VARIABLEPRIME, AND_TOKEN}] = {};
    table[{VARIABLEPRIME, WRITE_TOKEN}] = {};
    table[{VARIABLEPRIME, WRITELN_TOKEN}] = {};
    table[{VARIABLEPRIME, READ_TOKEN}] = {};
    table[{VARIABLEPRIME, READLN_TOKEN}] = {};
    // BLOCK
    table[{BLOCK, BEGIN_TOKEN}] = {BEGIN_TOKEN, STMTS, END_TOKEN};
    // STMTS
    table[{STMTS, ID_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, ';'}] = {STMT, STMTLISTPRIME};
    table[{STMTS, END_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, BEGIN_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, LABEL_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, EXITWHEN_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, RETURN_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, IF_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, LOOP_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, CASE_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, GOTO_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, FOR_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, WRITE_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, WRITELN_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, READ_TOKEN}] = {STMT, STMTLISTPRIME};
    table[{STMTS, READLN_TOKEN}] = {STMT, STMTLISTPRIME};
    // STMTLISTPRIME
    table[{STMTLISTPRIME, ';'}] = {';', STMTS};
    table[{STMTLISTPRIME, END_TOKEN}] = {};
    // STMT
    table[{STMT, WRITE_TOKEN}] = {WRITESTMT};
    table[{STMT, WRITELN_TOKEN}] = {WRITELNSTMT};
    table[{STMT, READ_TOKEN}] = {READSTMT};
    table[{STMT, READLN_TOKEN}] = {READLNSTMT};
    table[{STMT, FOR_TOKEN}] = {FORBLOCK};
    table[{STMT, ';'}] = {};
    table[{STMT, END_TOKEN}] = {};
    table[{STMT, BEGIN_TOKEN}] = {BLOCK};
    table[{STMT, LABEL_TOKEN}] = {LABEL_TOKEN, STMT};
    table[{STMT, EXITWHEN_TOKEN}] = {EXITSTMT};
    table[{STMT, ID_TOKEN}] = {ID_TOKEN, STMTPRIME};
    table[{STMT, RETURN_TOKEN}] = {RETURNSTMT};
    table[{STMT, IF_TOKEN}] = {IFBLOCK};
    table[{STMT, ELSE_TOKEN}] = {};
    table[{STMT, LOOP_TOKEN}] = {LOOPBLOCK};
    table[{STMT, CASE_TOKEN}] = {CASEBLOCK};
    table[{STMT, GOTO_TOKEN}] = {GOTOSTMT};
    // STMTPRIME
    table[{STMTPRIME, '['}] = {ATTRSTMT};
    table[{STMTPRIME, ACCESS_TOKEN}] = {ATTRSTMT};
    table[{STMTPRIME, ATTR_TOKEN}] = {ATTRSTMT};
    table[{STMTPRIME, '('}] = {SUBPROGCALL};
    // SUBPROGCALL
    table[{SUBPROGCALL, '('}] = {'(', EXPRLIST, ')'};
    // EXITSTMT
    table[{EXITSTMT, EXITWHEN_TOKEN}] = {EXITWHEN_TOKEN, EXPR};
    // RETURNSTMT
    table[{RETURNSTMT, RETURN_TOKEN}] = {RETURN_TOKEN, EXPR};
    // ATTRSTMT
    table[{ATTRSTMT, '['}] = {VARIABLE, ATTR_TOKEN, EXPR};
    table[{ATTRSTMT, ACCESS_TOKEN}] = {VARIABLE, ATTR_TOKEN, EXPR};
    table[{ATTRSTMT, ATTR_TOKEN}] = {ATTR_TOKEN, EXPR};
    // IFBLOCK
    table[{IFBLOCK, IF_TOKEN}] = {IF_TOKEN, EXPR, STMT, ELSEBLOCK};
    // ELSEBLOCK
    table[{ELSEBLOCK, ';'}] = {};
    table[{ELSEBLOCK, END_TOKEN}] = {};
    table[{ELSEBLOCK, ELSE_TOKEN}] = {ELSE_TOKEN, STMT};
    // LOOPBLOCK
    table[{LOOPBLOCK, LOOP_TOKEN}] = {LOOP_TOKEN, STMT};
    // CASEBLOCK
    table[{CASEBLOCK, CASE_TOKEN}] = {CASE_TOKEN, EXPR, OF_TOKEN, CASELIST, CASEBLOCKPRIME};
    // CASEBLOCKPRIME
    table[{CASEBLOCKPRIME, END_TOKEN}] = {END_TOKEN};
    table[{CASEBLOCKPRIME, ELSE_TOKEN}] = {ELSE_TOKEN, STMT, END_TOKEN};
    // CASELIST
    table[{CASELIST, INTLITERAL_TOKEN}] = {LITERALLIST, ':', STMT, ';'};
    table[{CASELIST, REALLITERAL_TOKEN}] = {LITERALLIST, ':', STMT, ';'};
    table[{CASELIST, CHARLITERAL_TOKEN}] = {LITERALLIST, ':', STMT, ';'};
    table[{CASELIST, STRINGLITERAL_TOKEN}] = {LITERALLIST, ':', STMT, ';'};
    table[{CASELIST, SUBRANGELITERAL_TOKEN}] = {LITERALLIST, ':', STMT, ';'};
    // LITERALLIST
    table[{LITERALLIST, INTLITERAL_TOKEN}] = {LITERAL, LITERALLISTPRIME};
    table[{LITERALLIST, REALLITERAL_TOKEN}] = {LITERAL, LITERALLISTPRIME};
    table[{LITERALLIST, CHARLITERAL_TOKEN}] = {LITERAL, LITERALLISTPRIME};
    table[{LITERALLIST, STRINGLITERAL_TOKEN}] = {LITERAL, LITERALLISTPRIME};
    table[{LITERALLIST, SUBRANGELITERAL_TOKEN}] = {LITERAL, LITERALLISTPRIME};
    // LITERALLISTPRIME
    table[{LITERALLISTPRIME, ','}] = {',', LITERALLIST};
    table[{LITERALLISTPRIME, ':'}] = {};
    // GOTOSTMT
    table[{GOTOSTMT, GOTO_TOKEN}] = {GOTO_TOKEN, LABEL_TOKEN};
    // FORBLOCK
    table[{FORBLOCK, FOR_TOKEN}] = {FOR_TOKEN, ID_TOKEN, FORBLOCKPRIME};
    // FORBLOCKPRIME
    table[{FORBLOCKPRIME, '['}] = {VARIABLE,  ATTR_TOKEN, EXPR, TO_TOKEN, EXPR, STEP_TOKEN, EXPR, DO_TOKEN, STMT};
    table[{FORBLOCKPRIME, ACCESS_TOKEN}] = {VARIABLE,  ATTR_TOKEN, EXPR, TO_TOKEN, EXPR, STEP_TOKEN, EXPR, DO_TOKEN, STMT};
    table[{FORBLOCKPRIME, ATTR_TOKEN}] = {ATTR_TOKEN, EXPR, TO_TOKEN, EXPR, STEP_TOKEN, EXPR, DO_TOKEN, STMT};
    // EXPR
    table[{EXPR, ID_TOKEN}] = {CONJ, DISJ};
    table[{EXPR, '('}] = {CONJ, DISJ};
    table[{EXPR, '!'}] = {CONJ, DISJ};
    table[{EXPR, INTLITERAL_TOKEN}] = {CONJ, DISJ};
    table[{EXPR, REALLITERAL_TOKEN}] = {CONJ, DISJ};
    table[{EXPR, CHARLITERAL_TOKEN}] = {CONJ, DISJ};
    table[{EXPR, STRINGLITERAL_TOKEN}] = {CONJ, DISJ};
    table[{EXPR, SUBRANGELITERAL_TOKEN}] = {CONJ, DISJ};
    // DISJ
    table[{DISJ, ID_TOKEN}] = {};
    table[{DISJ, ';'}] = {};
    table[{DISJ, ']'}] = {};
    table[{DISJ, OF_TOKEN}] = {};
    table[{DISJ, ','}] = {};
    table[{DISJ, ')'}] = {};
    table[{DISJ, END_TOKEN}] = {};
    table[{DISJ, BEGIN_TOKEN}] = {};
    table[{DISJ, LABEL_TOKEN}] = {};
    table[{DISJ, EXITWHEN_TOKEN}] = {};
    table[{DISJ, RETURN_TOKEN}] = {};
    table[{DISJ, IF_TOKEN}] = {};
    table[{DISJ, ELSE_TOKEN}] = {};
    table[{DISJ, LOOP_TOKEN}] = {};
    table[{DISJ, CASE_TOKEN}] = {};
    table[{DISJ, GOTO_TOKEN}] = {};
    table[{DISJ, FOR_TOKEN}] = {};
    table[{DISJ, TO_TOKEN}] = {};
    table[{DISJ, STEP_TOKEN}] = {};
    table[{DISJ, DO_TOKEN}] = {};
    table[{DISJ, WRITE_TOKEN}] = {};
    table[{DISJ, WRITELN_TOKEN}] = {};
    table[{DISJ, READ_TOKEN}] = {};
    table[{DISJ, READLN_TOKEN}] = {};
    table[{DISJ, OR_TOKEN}] = {OR_TOKEN, CONJ};
    // FINAL_TERM
    table[{FINAL_TERM, ID_TOKEN}] = {ID_TOKEN, FINAL_TERMPRIME};
    table[{FINAL_TERM, INTLITERAL_TOKEN}] = {LITERAL};
    table[{FINAL_TERM, REALLITERAL_TOKEN}] = {LITERAL};
    table[{FINAL_TERM, CHARLITERAL_TOKEN}] = {LITERAL};
    table[{FINAL_TERM, STRINGLITERAL_TOKEN}] = {LITERAL};
    table[{FINAL_TERM, SUBRANGELITERAL_TOKEN}] = {LITERAL};
    table[{FINAL_TERM, '('}] = {'(', EXPR, ')'};
    // FINAL_TERMPRIME
    table[{FINAL_TERMPRIME, ID_TOKEN}] = {};
    table[{FINAL_TERMPRIME, ';'}] = {};
    table[{FINAL_TERMPRIME, '['}] = {VARIABLE};
    table[{FINAL_TERMPRIME, ']'}] = {};
    table[{FINAL_TERMPRIME, OF_TOKEN}] = {};
    table[{FINAL_TERMPRIME, ','}] = {};
    table[{FINAL_TERMPRIME, '('}] = {SUBPROGCALL};
    table[{FINAL_TERMPRIME, ')'}] = {};
    table[{FINAL_TERMPRIME, END_TOKEN}] = {};
    table[{FINAL_TERMPRIME, ACCESS_TOKEN}] = {VARIABLE};
    table[{FINAL_TERMPRIME, BEGIN_TOKEN}] = {};
    table[{FINAL_TERMPRIME, LABEL_TOKEN}] = {};
    table[{FINAL_TERMPRIME, EXITWHEN_TOKEN}] = {};
    table[{FINAL_TERMPRIME, RETURN_TOKEN}] = {};
    table[{FINAL_TERMPRIME, IF_TOKEN}] = {};
    table[{FINAL_TERMPRIME, ELSE_TOKEN}] = {};
    table[{FINAL_TERMPRIME, LOOP_TOKEN}] = {};
    table[{FINAL_TERMPRIME, CASE_TOKEN}] = {};
    table[{FINAL_TERMPRIME, GOTO_TOKEN}] = {};
    table[{FINAL_TERMPRIME, FOR_TOKEN}] = {};
    table[{FINAL_TERMPRIME, TO_TOKEN}] = {};
    table[{FINAL_TERMPRIME, STEP_TOKEN}] = {};
    table[{FINAL_TERMPRIME, DO_TOKEN}] = {};
    table[{FINAL_TERMPRIME, OR_TOKEN}] = {};
    table[{FINAL_TERMPRIME, '+'}] = {};
    table[{FINAL_TERMPRIME, '-'}] = {};
    table[{FINAL_TERMPRIME, '*'}] = {};
    table[{FINAL_TERMPRIME, '/'}] = {};
    table[{FINAL_TERMPRIME, '%'}] = {};
    table[{FINAL_TERMPRIME, EQUAL_TOKEN}] = {};
    table[{FINAL_TERMPRIME, DIFF_TOKEN}] = {};
    table[{FINAL_TERMPRIME, '<'}] = {};
    table[{FINAL_TERMPRIME, LE_TOKEN}] = {};
    table[{FINAL_TERMPRIME, '>'}] = {};
    table[{FINAL_TERMPRIME, GE_TOKEN}] = {};
    table[{FINAL_TERMPRIME, AND_TOKEN}] = {};
    table[{FINAL_TERMPRIME, WRITE_TOKEN}] = {};
    table[{FINAL_TERMPRIME, WRITELN_TOKEN}] = {};
    table[{FINAL_TERMPRIME, READ_TOKEN}] = {};
    table[{FINAL_TERMPRIME, READLN_TOKEN}] = {};
    // ADD_OP
    table[{ADD_OP, '+'}] = {'+'};
    table[{ADD_OP, '-'}] = {'-'};
    // MUL_OP
    table[{MUL_OP, '*'}] = {'*'};
    table[{MUL_OP, '/'}] = {'/'};
    table[{MUL_OP, '%'}] = {'%'};
    // EQUALITY_OP
    table[{EQUALITY_OP, EQUAL_TOKEN}] = {EQUAL_TOKEN};
    table[{EQUALITY_OP, DIFF_TOKEN}] = {DIFF_TOKEN};
    // RELATIONAL_OP
    table[{RELATIONAL_OP, '<'}] = {'<'};
    table[{RELATIONAL_OP, '>'}] = {'>'};
    table[{RELATIONAL_OP, LE_TOKEN}] = {LE_TOKEN};
    table[{RELATIONAL_OP, GE_TOKEN}] = {GE_TOKEN};
    // CONJ
    table[{CONJ, ID_TOKEN}] = {COMP, CONJPRIME};
    table[{CONJ, '('}] = {COMP, CONJPRIME};
    table[{CONJ, '!'}] = {COMP, CONJPRIME};
    table[{CONJ, INTLITERAL_TOKEN}] = {COMP, CONJPRIME};
    table[{CONJ, REALLITERAL_TOKEN}] = {COMP, CONJPRIME};
    table[{CONJ, CHARLITERAL_TOKEN}] = {COMP, CONJPRIME};
    table[{CONJ, STRINGLITERAL_TOKEN}] = {COMP, CONJPRIME};
    table[{CONJ, SUBRANGELITERAL_TOKEN}] = {COMP, CONJPRIME};
    // CONJPRIME
    table[{CONJPRIME, ID_TOKEN}] = {};
    table[{CONJPRIME, ';'}] = {};
    table[{CONJPRIME, ']'}] = {};
    table[{CONJPRIME, OF_TOKEN}] = {};
    table[{CONJPRIME, ','}] = {};
    table[{CONJPRIME, ')'}] = {};
    table[{CONJPRIME, END_TOKEN}] = {};
    table[{CONJPRIME, BEGIN_TOKEN}] = {};
    table[{CONJPRIME, LABEL_TOKEN}] = {};
    table[{CONJPRIME, EXITWHEN_TOKEN}] = {};
    table[{CONJPRIME, RETURN_TOKEN}] = {};
    table[{CONJPRIME, IF_TOKEN}] = {};
    table[{CONJPRIME, ELSE_TOKEN}] = {};
    table[{CONJPRIME, LOOP_TOKEN}] = {};
    table[{CONJPRIME, CASE_TOKEN}] = {};
    table[{CONJPRIME, GOTO_TOKEN}] = {};
    table[{CONJPRIME, FOR_TOKEN}] = {};
    table[{CONJPRIME, TO_TOKEN}] = {};
    table[{CONJPRIME, STEP_TOKEN}] = {};
    table[{CONJPRIME, DO_TOKEN}] = {};
    table[{CONJPRIME, OR_TOKEN}] = {};
    table[{CONJPRIME, WRITE_TOKEN}] = {};
    table[{CONJPRIME, WRITELN_TOKEN}] = {};
    table[{CONJPRIME, READ_TOKEN}] = {};
    table[{CONJPRIME, READLN_TOKEN}] = {};
    table[{CONJPRIME, AND_TOKEN}] = {AND_TOKEN, COMP};
    // COMP
    table[{COMP, ID_TOKEN}] = {RELATIONAL, COMPPRIME};
    table[{COMP, '('}] = {RELATIONAL, COMPPRIME};
    table[{COMP, '!'}] = {RELATIONAL, COMPPRIME};
    table[{COMP, INTLITERAL_TOKEN}] = {RELATIONAL, COMPPRIME};
    table[{COMP, REALLITERAL_TOKEN}] = {RELATIONAL, COMPPRIME};
    table[{COMP, CHARLITERAL_TOKEN}] = {RELATIONAL, COMPPRIME};
    table[{COMP, STRINGLITERAL_TOKEN}] = {RELATIONAL, COMPPRIME};
    table[{COMP, SUBRANGELITERAL_TOKEN}] = {RELATIONAL, COMPPRIME};
    // COMPPRIME
    table[{COMPPRIME, ID_TOKEN}] = {};
    table[{COMPPRIME, ';'}] = {};
    table[{COMPPRIME, ']'}] = {};
    table[{COMPPRIME, OF_TOKEN}] = {};
    table[{COMPPRIME, ','}] = {};
    table[{COMPPRIME, ')'}] = {};
    table[{COMPPRIME, END_TOKEN}] = {};
    table[{COMPPRIME, BEGIN_TOKEN}] = {};
    table[{COMPPRIME, LABEL_TOKEN}] = {};
    table[{COMPPRIME, EXITWHEN_TOKEN}] = {};
    table[{COMPPRIME, RETURN_TOKEN}] = {};
    table[{COMPPRIME, IF_TOKEN}] = {};
    table[{COMPPRIME, ELSE_TOKEN}] = {};
    table[{COMPPRIME, LOOP_TOKEN}] = {};
    table[{COMPPRIME, CASE_TOKEN}] = {};
    table[{COMPPRIME, GOTO_TOKEN}] = {};
    table[{COMPPRIME, FOR_TOKEN}] = {};
    table[{COMPPRIME, TO_TOKEN}] = {};
    table[{COMPPRIME, STEP_TOKEN}] = {};
    table[{COMPPRIME, DO_TOKEN}] = {};
    table[{COMPPRIME, OR_TOKEN}] = {};
    table[{COMPPRIME, AND_TOKEN}] = {};
    table[{COMPPRIME, WRITE_TOKEN}] = {};
    table[{COMPPRIME, WRITELN_TOKEN}] = {};
    table[{COMPPRIME, READ_TOKEN}] = {};
    table[{COMPPRIME, READLN_TOKEN}] = {};
    table[{COMPPRIME, EQUAL_TOKEN}] = {EQUALITY_OP, RELATIONAL};
    table[{COMPPRIME, DIFF_TOKEN}] = {EQUALITY_OP, RELATIONAL};
    // RELATIONAL
    table[{RELATIONAL, ID_TOKEN}] = {SUM, RELATIONALPRIME};
    table[{RELATIONAL, '('}] = {SUM, RELATIONALPRIME};
    table[{RELATIONAL, '!'}] = {SUM, RELATIONALPRIME};
    table[{RELATIONAL, INTLITERAL_TOKEN}] = {SUM, RELATIONALPRIME};
    table[{RELATIONAL, REALLITERAL_TOKEN}] = {SUM, RELATIONALPRIME};
    table[{RELATIONAL, CHARLITERAL_TOKEN}] = {SUM, RELATIONALPRIME};
    table[{RELATIONAL, STRINGLITERAL_TOKEN}] = {SUM, RELATIONALPRIME};
    table[{RELATIONAL, SUBRANGELITERAL_TOKEN}] = {SUM, RELATIONALPRIME};
    // RELATIONALPRIME
    table[{RELATIONALPRIME, ID_TOKEN}] = {};
    table[{RELATIONALPRIME, ';'}] = {};
    table[{RELATIONALPRIME, ']'}] = {};
    table[{RELATIONALPRIME, OF_TOKEN}] = {};
    table[{RELATIONALPRIME, ','}] = {};
    table[{RELATIONALPRIME, ')'}] = {};
    table[{RELATIONALPRIME, END_TOKEN}] = {};
    table[{RELATIONALPRIME, BEGIN_TOKEN}] = {};
    table[{RELATIONALPRIME, LABEL_TOKEN}] = {};
    table[{RELATIONALPRIME, EXITWHEN_TOKEN}] = {};
    table[{RELATIONALPRIME, RETURN_TOKEN}] = {};
    table[{RELATIONALPRIME, IF_TOKEN}] = {};
    table[{RELATIONALPRIME, ELSE_TOKEN}] = {};
    table[{RELATIONALPRIME, LOOP_TOKEN}] = {};
    table[{RELATIONALPRIME, CASE_TOKEN}] = {};
    table[{RELATIONALPRIME, GOTO_TOKEN}] = {};
    table[{RELATIONALPRIME, FOR_TOKEN}] = {};
    table[{RELATIONALPRIME, TO_TOKEN}] = {};
    table[{RELATIONALPRIME, STEP_TOKEN}] = {};
    table[{RELATIONALPRIME, DO_TOKEN}] = {};
    table[{RELATIONALPRIME, OR_TOKEN}] = {};
    table[{RELATIONALPRIME, EQUAL_TOKEN}] = {};
    table[{RELATIONALPRIME, DIFF_TOKEN}] = {};
    table[{RELATIONALPRIME, AND_TOKEN}] = {};
    table[{RELATIONALPRIME, WRITE_TOKEN}] = {};
    table[{RELATIONALPRIME, WRITELN_TOKEN}] = {};
    table[{RELATIONALPRIME, READ_TOKEN}] = {};
    table[{RELATIONALPRIME, READLN_TOKEN}] = {};
    table[{RELATIONALPRIME, '<'}] = {RELATIONAL_OP, SUM};
    table[{RELATIONALPRIME, LE_TOKEN}] = {RELATIONAL_OP, SUM};
    table[{RELATIONALPRIME, '>'}] = {RELATIONAL_OP, SUM};
    table[{RELATIONALPRIME, GE_TOKEN}] = {RELATIONAL_OP, SUM};
    // SUM
    table[{SUM, ID_TOKEN}] = {NEG, SUMPRIME};
    table[{SUM, '('}] = {NEG, SUMPRIME};
    table[{SUM, '!'}] = {NEG, SUMPRIME};
    table[{SUM, INTLITERAL_TOKEN}] = {NEG, SUMPRIME};
    table[{SUM, REALLITERAL_TOKEN}] = {NEG, SUMPRIME};
    table[{SUM, CHARLITERAL_TOKEN}] = {NEG, SUMPRIME};
    table[{SUM, STRINGLITERAL_TOKEN}] = {NEG, SUMPRIME};
    table[{SUM, SUBRANGELITERAL_TOKEN}] = {NEG, SUMPRIME};
    // SUMPRIME
    table[{SUMPRIME, ID_TOKEN}] = {};
    table[{SUMPRIME, ';'}] = {};
    table[{SUMPRIME, ']'}] = {};
    table[{SUMPRIME, OF_TOKEN}] = {};
    table[{SUMPRIME, ','}] = {};
    table[{SUMPRIME, ')'}] = {};
    table[{SUMPRIME, END_TOKEN}] = {};
    table[{SUMPRIME, BEGIN_TOKEN}] = {};
    table[{SUMPRIME, LABEL_TOKEN}] = {};
    table[{SUMPRIME, EXITWHEN_TOKEN}] = {};
    table[{SUMPRIME, RETURN_TOKEN}] = {};
    table[{SUMPRIME, IF_TOKEN}] = {};
    table[{SUMPRIME, ELSE_TOKEN}] = {};
    table[{SUMPRIME, LOOP_TOKEN}] = {};
    table[{SUMPRIME, CASE_TOKEN}] = {};
    table[{SUMPRIME, GOTO_TOKEN}] = {};
    table[{SUMPRIME, FOR_TOKEN}] = {};
    table[{SUMPRIME, TO_TOKEN}] = {};
    table[{SUMPRIME, STEP_TOKEN}] = {};
    table[{SUMPRIME, DO_TOKEN}] = {};
    table[{SUMPRIME, OR_TOKEN}] = {};
    table[{SUMPRIME, EQUAL_TOKEN}] = {};
    table[{SUMPRIME, DIFF_TOKEN}] = {};
    table[{SUMPRIME, '<'}] = {};
    table[{SUMPRIME, LE_TOKEN}] = {};
    table[{SUMPRIME, '>'}] = {};
    table[{SUMPRIME, GE_TOKEN}] = {};
    table[{SUMPRIME, AND_TOKEN}] = {};
    table[{SUMPRIME, WRITE_TOKEN}] = {};
    table[{SUMPRIME, WRITELN_TOKEN}] = {};
    table[{SUMPRIME, READ_TOKEN}] = {};
    table[{SUMPRIME, READLN_TOKEN}] = {};
    table[{SUMPRIME, '+'}] = {ADD_OP, NEG, SUMPRIME};
    table[{SUMPRIME, '-'}] = {ADD_OP, NEG, SUMPRIME};
    // NEG
    table[{NEG, ID_TOKEN}] = {MUL};
    table[{NEG, '('}] = {MUL};
    table[{NEG, INTLITERAL_TOKEN}] = {MUL};
    table[{NEG, REALLITERAL_TOKEN}] = {MUL};
    table[{NEG, CHARLITERAL_TOKEN}] = {MUL};
    table[{NEG, STRINGLITERAL_TOKEN}] = {MUL};
    table[{NEG, SUBRANGELITERAL_TOKEN}] = {MUL};
    table[{NEG, '!'}] = {'!', MUL};
    // MUL
    table[{MUL, ID_TOKEN}] = {FINAL_TERM, MULPRIME};
    table[{MUL, '('}] = {FINAL_TERM, MULPRIME};
    table[{MUL, INTLITERAL_TOKEN}] = {FINAL_TERM, MULPRIME};
    table[{MUL, REALLITERAL_TOKEN}] = {FINAL_TERM, MULPRIME};
    table[{MUL, CHARLITERAL_TOKEN}] = {FINAL_TERM, MULPRIME};
    table[{MUL, STRINGLITERAL_TOKEN}] = {FINAL_TERM, MULPRIME};
    table[{MUL, SUBRANGELITERAL_TOKEN}] = {FINAL_TERM, MULPRIME};
    // MULPRIME
    table[{MULPRIME, ID_TOKEN}] = {};
    table[{MULPRIME, ';'}] = {};
    table[{MULPRIME, ']'}] = {};
    table[{MULPRIME, OF_TOKEN}] = {};
    table[{MULPRIME, ','}] = {};
    table[{MULPRIME, ')'}] = {};
    table[{MULPRIME, END_TOKEN}] = {};
    table[{MULPRIME, BEGIN_TOKEN}] = {};
    table[{MULPRIME, LABEL_TOKEN}] = {};
    table[{MULPRIME, EXITWHEN_TOKEN}] = {};
    table[{MULPRIME, RETURN_TOKEN}] = {};
    table[{MULPRIME, IF_TOKEN}] = {};
    table[{MULPRIME, ELSE_TOKEN}] = {};
    table[{MULPRIME, LOOP_TOKEN}] = {};
    table[{MULPRIME, CASE_TOKEN}] = {};
    table[{MULPRIME, GOTO_TOKEN}] = {};
    table[{MULPRIME, FOR_TOKEN}] = {};
    table[{MULPRIME, TO_TOKEN}] = {};
    table[{MULPRIME, STEP_TOKEN}] = {};
    table[{MULPRIME, DO_TOKEN}] = {};
    table[{MULPRIME, OR_TOKEN}] = {};
    table[{MULPRIME, '+'}] = {};
    table[{MULPRIME, '-'}] = {};
    table[{MULPRIME, EQUAL_TOKEN}] = {};
    table[{MULPRIME, DIFF_TOKEN}] = {};
    table[{MULPRIME, '<'}] = {};
    table[{MULPRIME, LE_TOKEN}] = {};
    table[{MULPRIME, '>'}] = {};
    table[{MULPRIME, GE_TOKEN}] = {};
    table[{MULPRIME, AND_TOKEN}] = {};
    table[{MULPRIME, WRITE_TOKEN}] = {};
    table[{MULPRIME, WRITELN_TOKEN}] = {};
    table[{MULPRIME, READ_TOKEN}] = {};
    table[{MULPRIME, READLN_TOKEN}] = {};
    table[{MULPRIME, '*'}] = {MUL_OP, FINAL_TERM, MULPRIME};
    table[{MULPRIME, '/'}] = {MUL_OP, FINAL_TERM, MULPRIME};
    table[{MULPRIME, '%'}] = {MUL_OP, FINAL_TERM, MULPRIME};
    // LITERAL
    table[{LITERAL, INTLITERAL_TOKEN}] = {INTLITERAL_TOKEN};
    table[{LITERAL, REALLITERAL_TOKEN}] = {REALLITERAL_TOKEN};
    table[{LITERAL, CHARLITERAL_TOKEN}] = {CHARLITERAL_TOKEN};
    table[{LITERAL, STRINGLITERAL_TOKEN}] = {STRINGLITERAL_TOKEN};
    table[{LITERAL, SUBRANGELITERAL_TOKEN}] = {SUBRANGELITERAL_TOKEN};
    // EXPRLIST
    table[{EXPRLIST, ')'}] = {};
    table[{EXPRLIST, ID_TOKEN}] = {EXPRLISTPLUS};
    table[{EXPRLIST, '('}] = {EXPRLISTPLUS};
    table[{EXPRLIST, '!'}] = {EXPRLISTPLUS};
    table[{EXPRLIST, INTLITERAL_TOKEN}] = {EXPRLISTPLUS};
    table[{EXPRLIST, REALLITERAL_TOKEN}] = {EXPRLISTPLUS};
    table[{EXPRLIST, CHARLITERAL_TOKEN}] = {EXPRLISTPLUS};
    table[{EXPRLIST, STRINGLITERAL_TOKEN}] = {EXPRLISTPLUS};
    table[{EXPRLIST, SUBRANGELITERAL_TOKEN}] = {EXPRLISTPLUS};
    // EXPRLISTPLUS
    table[{EXPRLISTPLUS, ID_TOKEN}] = {EXPR, EXPRLISTPLUSPRIME};
    table[{EXPRLISTPLUS, '('}] = {EXPR, EXPRLISTPLUSPRIME};
    table[{EXPRLISTPLUS, '!'}] = {EXPR, EXPRLISTPLUSPRIME};
    table[{EXPRLISTPLUS, INTLITERAL_TOKEN}] = {EXPR, EXPRLISTPLUSPRIME};
    table[{EXPRLISTPLUS, REALLITERAL_TOKEN}] = {EXPR, EXPRLISTPLUSPRIME};
    table[{EXPRLISTPLUS, CHARLITERAL_TOKEN}] = {EXPR, EXPRLISTPLUSPRIME};
    table[{EXPRLISTPLUS, STRINGLITERAL_TOKEN}] = {EXPR, EXPRLISTPLUSPRIME};
    table[{EXPRLISTPLUS, SUBRANGELITERAL_TOKEN}] = {EXPR, EXPRLISTPLUSPRIME};
    // EXPRLISTPLUSPRIME
    table[{EXPRLISTPLUSPRIME, ']'}] = {};
    table[{EXPRLISTPLUSPRIME, ')'}] = {};
    table[{EXPRLISTPLUSPRIME, ','}] = {',', EXPRLISTPLUS};
    // SUBPROGRAMS
    table[{SUBPROGRAMS, BEGIN_TOKEN}] = {};
    table[{SUBPROGRAMS, PROC_TOKEN}] = {PROCEDURE, SUBPROGRAMSPRIME};
    table[{SUBPROGRAMS, FUNC_TOKEN}] = {FUNCTION, SUBPROGRAMSPRIME};
    // SUBPROGRAMSPRIME
    table[{SUBPROGRAMSPRIME, BEGIN_TOKEN}] = {};
    table[{SUBPROGRAMSPRIME, ';'}] = {';', SUBPROGRAMS};
    // PROCEDURE
    table[{PROCEDURE, PROC_TOKEN}] = {PROC_TOKEN, ID_TOKEN, '(', PARAM, ')', ';', DECL, BLOCK};
    // FUNCTION
    table[{FUNCTION, FUNC_TOKEN}] = {FUNC_TOKEN, TYPES, ID_TOKEN, '(', PARAM, ')', ';', DECL, BLOCK};
    // PARAM
    table[{PARAM, ')'}] = {};
    table[{PARAM, ID_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, INT_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, REAL_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, BOOL_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, CHAR_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, STRING_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, ARRAY_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, SET_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, '('}] = {PARAMLISTLIST};
    table[{PARAM, RECORD_TOKEN}] = {PARAMLISTLIST};
    table[{PARAM, REF_TOKEN}] = {PARAMLISTLIST};
    // PARAMLISTLIST
    table[{PARAMLISTLIST, ID_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, INT_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, REAL_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, BOOL_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, CHAR_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, STRING_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, ARRAY_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, SET_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, '('}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, RECORD_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    table[{PARAMLISTLIST, REF_TOKEN}] = {PARAMLIST, PARAMLISTLISTPRIME};
    // PARAMLISTLISTPRIME
    table[{PARAMLISTLISTPRIME, ')'}] = {};
    table[{PARAMLISTLISTPRIME, ';'}] = {';', PARAMLISTLIST};
    // PARAMLIST
    table[{PARAMLIST, ID_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, INT_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, REAL_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, BOOL_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, CHAR_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, STRING_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, ARRAY_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, SET_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, '('}] = {TYPES, IDLIST};
    table[{PARAMLIST, RECORD_TOKEN}] = {TYPES, IDLIST};
    table[{PARAMLIST, REF_TOKEN}] = {REF_TOKEN, TYPES, IDLIST};
    // WRITESTMT
    table[{WRITESTMT, WRITE_TOKEN}] = {WRITE_TOKEN, '(', EXPR, ')',};
    // WRITELNSTMT
    table[{WRITELNSTMT, WRITELN_TOKEN}] = {WRITELN_TOKEN, '(', EXPR, ')'};
    // READSTMT
    table[{READSTMT, READ_TOKEN}] = {READ_TOKEN, '(', ID_TOKEN, VARIABLEPRIME, ')'};
    // READLNSTMT
    table[{READLNSTMT, READLN_TOKEN}] = {READLN_TOKEN, '(', ID_TOKEN, VARIABLEPRIME, ')'};
}

#endif
